version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
    ports:
      - "8083:8083"

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'exampledb'
      MYSQL_USER: 'exampleuser'
      MYSQL_PASSWORD: 'examplepass'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"